locus = "CGCTGGGGACCTGGGAAAGAGGGAAAGGCTTCCCCGGCCAGCTGCGCGGCGACTCCGGGGACTCCAGGGCGCCCCTCTGCGGCCGACGCCCGGGGTGCAGCGGCCGCCGGGGCTGGGGCCGGCGGGAGTCCGCGGGACCCTCCAGAAGAGCGGCCGGCGCCGTGACTCAGCACTGGGGCGGAGCGGGGCGGGACCACCCTTATAAGGCTCGGAGGCCGCGAGGCCTTCGCTGGAGTTTCGCCGCCGCAGTCTTCGCCACCAGTGAGTACGCGCGGCCCGCGTCCCCGGGGATGGGGCTCAGAGCTCCCAGCATGGGGCCAACCCG"
tss_sequence = "GGAGTTTCGCCGCCGCA"

tss = locus.find(tss_sequence)
print(tss)

previous_cpg = -1
for i in range(1,40):
    current_cpg = locus.find("CG", previous_cpg + 1)
    print(f"CpG_{i}: {current_cpg-tss}")
    previous_cpg = current_cpg